### ISSUE TITLE
ArchiveBox shipping with Dev version, which is unstable

### ISSUE THREAD

**Issue by readtedium** [TinyActive/cosmos-servapps#14]
**Describe the bug**

I recently updated my version of ArchiveBox, which introduced a bug. (Actually, Cosmos auto-updated it.) When I looked into information about it, I found that it was the result of the container being on the `dev` branch, which the developer [is warning is an unstable branch](https://github.com/ArchiveBox/ArchiveBox/issues/1391).

I was ultimately able to resolve it by downgrading it to an earlier version and removing a variable.

**To Reproduce**
1. Upgrade ArchiveBox to latest version in dev path, whether manually or automatically.

**Expected behavior**

An updated version of the tool working with no problems.

**Additional context**

Given that these packages are designed for trying different tools, it may help to avoid `dev` branches where possible. An easy fix, but will prevent a lot of headaches.

**Comment by vncloudsco** [comment]
Thanks for reporting we have updated
