### ISSUE TITLE
DiskStation Create issue

### ISSUE THREAD

**Issue by UnKwang9** [TinyActive/cosmos-servapps#18]
**Describe the bug**
There is a issue with the DiskStation/cosmos-compose.json file.
I installed it by deleting the stop_grace_period line.

**To Reproduce**
1. Go to 'Market'
2. Click on 'DiskStation@TinyActive'
3. Click on 'Install'
4. Leave the defaults as they are and Click on 'Next'
5. Click on 'Create'
6. See error

**Screenshots**
![image](https://github.com/user-attachments/assets/8e7a55f7-9bef-4623-86f2-b6290332bbd5)

**Additional context**
The version of cosmos I'm using is 0.15.7

**Comment by vncloudsco** [comment]
The error has been fixed.
detail: 
The error you're encountering is caused by the value "stop_grace_period": "1m" being passed as a string, while Go requires an integer data type
