### ISSUE TITLE
Coder's recent commit makes it into appwrite, is this intentional?

### ISSUE THREAD

**Issue by lilkidsuave** [TinyActive/cosmos-servapps#7]

**Comment by vncloudsco** [comment]
I don't understand what your question is? Please let me know more details.

**Comment by lilkidsuave** [comment]
The image gets completely changed and so does many other parts for the compose.
![Screenshot_20231221_142849_Brave](https://github.com/TinyActive/cosmos-servapps/assets/66171643/b7fb10fc-61a5-41f8-bd37-ba786c6df46e)

**Comment by vncloudsco** [comment]
Thanks for reporting I have corrected this mistake, it was found incorrectly when I tested it appwrite. mayny thank!
